### ISSUE TITLE
Generate arn?

### ISSUE THREAD

**Issue by foresmac** [PokaInc/arnparse#2]
Seems like it would be useful for the `Arn` class to have a method to generate a valid ARN—i.e., `arnparse` in reverse, like [`geturl()`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urllib.parse.SplitResult.geturl) in `urlparse`.

**Comment by spg** [comment]
What use case(s) did you have in mind?

**Comment by foresmac** [comment]
TBH, I don't really have one off the top of my head. I just know that a lot of AWS APIs use those ARNs, and I was thinking there's probably a time when you need to go the other way to do something useful. E.g., parse the ARN, change one of the properties, rebuild that ARN to fix something?

**Comment by foresmac** [comment]
OTOH, I imagine boto probably handles that internally in a way you don't need to think about it, though.

**Comment by spg** [comment]
I agree, it might come in useful in the future. 
I'll wait for a concrete use case before going ahead with this.
Thanks for the suggestion!
