### ISSUE TITLE
Fails to parse EBS volume ARN

### ISSUE THREAD

**Issue by schosterbarak** [PokaInc/arnparse#8]
Value like:
        "arn:aws:us-west-2:XXX:volume/YYY"
Replace XXX with account-id ad YYY with volume-id
throws
```
[ERROR] IndexError: list index out of range
  File "/var/task/arnparse/arnparse.py", line 30, in arnparse
    resource = elements[5]
```

**Comment by schosterbarak** [comment]
Suggested fix: https://github.com/PokaInc/arnparse/pull/9 @spg would you mind taking a look?

**Comment by laurrentt** [comment]
@schosterbarak I saw that you've closed the issue. Do you mind closing the Pull Request as well? Thank you 🙂
